authorName: Group 16
experimentName: CIFAR10 HPO
trialConcurrency: 1
maxExecDuration: 10h
maxTrialNum: 20
#choice: local, remote, pai
trainingServicePlatform: local
#localConfig:
#  gpuIndices: '0'
searchSpacePath: search_space_nni.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python main.py --epochs 30
  codeDir: .
  gpuNum: 1
